###############################################################################
#
# Makefile
#
# Packer Makefile template
#
###############################################################################

.DEFAULT_GOAL := all

vbox:
	@echo "Building for vbox"
	cd vbox && make

vsphere:
	@echo "Building for vsphere"
	cd vsphere && make

all: vbox vsphere

