###############################################################################
#
# Makefile
#
# Packer Makefile template
#
###############################################################################

PACKER = /usr/local/bin/packer
PACKER_FILE = config.json
PACKER_BUILD_OPTS = -timestamp-ui

.DEFAULT_GOAL := all

kickflip:
	../shared/kickstart/kickflip flip

debug:
	$(PACKER) build $(PACKER_BUILD_OPTS) -debug $(PACKER_FILE)

build: kickflip
	$(PACKER) build $(PACKER_BUILD_OPTS) $(PACKER_FILE)

validate:
	$(PACKER) validate $(PACKER_FILE)

inspect:
	$(PACKER) inspect $(PACKER_FILE)

all: validate build

clean:
	rm -fr stuff

distclean: clean
	rm -fr more_stuff

