###############################################################################
#
# Makefile
#
# Packer Makefile template
#
###############################################################################

PACKER = /usr/local/bin/packer
PACKER_FILE = kali2021-vbox-iso.json
PACKER_BUILD_OPTS = -timestamp-ui

.DEFAULT_GOAL := all


all: vbox vsphere

